//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstonePG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleFrequency
    {
        public string cycleFrequencyID { get; set; }
        public string obsAssignmentID { get; set; }
        public int cycleNumber { get; set; }
        public string cycleFrequencyCount { get; set; }
    
        public virtual ObservationAssignment ObservationAssignment { get; set; }
    }
}
