//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstonePG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineTiming
    {
        public string mtID { get; set; }
        public string whID { get; set; }
        public string mtMachineType { get; set; }
        public Nullable<System.DateTime> myStartAt { get; set; }
        public Nullable<System.DateTime> myEndAt { get; set; }
        public Nullable<int> mtDistance { get; set; }
        public Nullable<System.DateTime> mtStartTime { get; set; }
        public Nullable<System.DateTime> myEndTime { get; set; }
        public Nullable<System.DateTime> myDuration { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
