//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstonePG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservationTransaction
    {
        public string observationTransID { get; set; }
        public string observationSheetID { get; set; }
        public string observationTransDesc { get; set; }
    
        public virtual ObservationSheet ObservationSheet { get; set; }
    }
}
