//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstonePG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredMethod
    {
        public PreferredMethod()
        {
            this.ObservationSheets = new HashSet<ObservationSheet>();
            this.WarehouseMethods = new HashSet<WarehouseMethod>();
            this.PrefMethLines = new HashSet<PrefMethLine>();
        }
    
        public string prefMethID { get; set; }
        public string whID { get; set; }
        public string prefMethName { get; set; }
        public string prefMethDesc { get; set; }
    
        public virtual ICollection<ObservationSheet> ObservationSheets { get; set; }
        public virtual ICollection<WarehouseMethod> WarehouseMethods { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<PrefMethLine> PrefMethLines { get; set; }
    }
}
