//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstonePG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseMethod
    {
        public string wareMethID { get; set; }
        public string whID { get; set; }
        public string prefMethID { get; set; }
    
        public virtual PreferredMethod PreferredMethod { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
